### ISSUE TITLE
Invitation Table seperate of Users table 

### ISSUE THREAD

**Issue by harshamv** [scambra/devise_invitable#575] opened 2015-07-20 08:58 UTC
Is there a way i can have a separate Invitations table and allow users to be able to invite users to a particular account

```
users has_many accounts
```

Models
```
users(id, name, email,....)
accounts(id, name, user_id)
invitations(id, ..........., user_id, account_id)
```

This is the kind of implementation i want to do. Is it possible to use this gem to handle it?

**Comment by scambra** [comment] 2015-07-20 09:54
duplicate of #388

**Comment by scambra** [comment] 2015-07-20 09:54
Not possible right now, behaviour must be changed, as requested on #388

**Closed by scambra** 2015-07-20 09:54 UTC
