### ISSUE TITLE
wrong number of arguments (given 3, expected 1..2) 0n send_devise_notfication

### ISSUE THREAD

**Issue by thestumonkey** [scambra/devise_invitable#705] opened 2017-03-15 01:05 UTC
When I submit the invitation form, it seems to create the user and token ok in the DB, but fails actually sending the email with this error.  In fact, if I use a custom controller and skip the email sending part, it all works fine.  Any thoughts?  I'm stumped

```
wrong number of arguments (given 3, expected 1..2)    
      # processing instead of sending it inline as devise does by
      # default.
      def send_devise_notification(notification, opts = {})
        return super unless Devise::Async.enabled

        # If the record is dirty we keep pending notifications to be enqueued

devise-async (0.7.0) lib/devise/async/model.rb:27:in `send_devise_notification'
devise_invitable (1.7.1) lib/devise_invitable/model.rb:195:in `deliver_invitation'
devise_invitable (1.7.1) lib/devise_invitable/model.rb:153:in `block in invite!'
activesupport (4.2.5.2) lib/active_support/callbacks.rb:88:in `__run_callbacks__'
activesupport (4.2.5.2) lib/active_support/callbacks.rb:778:in `_run_invitation_created_callbacks'
activesupport (4.2.5.2) lib/active_support/callbacks.rb:81:in `run_callbacks'
airbrake (5.8.1) lib/airbrake/rails/active_record.rb:22:in `run_callbacks'`
```

**Comment by scambra** [comment] 2017-03-15 13:24
duplicate of #661

send_devise_notification definition:
https://github.com/plataformatec/devise/blob/88724e10adaf9ffd1d8dbfbaadda2b9d40de756a/lib/devise/models/authenticatable.rb#L187

call to send_devise_notification in devise:
https://github.com/plataformatec/devise/blob/0c5d78e31ca7589c2f637658c27ebe7b0e36dcd7/lib/devise/models/recoverable.rb#L97

call to send_devise_notification in devise invitable:
https://github.com/scambra/devise_invitable/blob/master/lib/devise_invitable/model.rb#L195

**Closed by scambra** 2017-03-15 13:24 UTC
